# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    restart: always
    # маршрутизируем порты
    ports:
      - "8050:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    container_name: ${PROJECT_NAME}-php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    restart: always
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектом
    volumes:
      - ../:/var/www
  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${PROJECT_NAME}
    ports:
      - 3305:3306
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    container_name: ${PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8051:80
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql
